### PR TITLE
Docker branch

### PR DESCRIPTION
**Pull request by donadivarun**
Small changes for some files. need to go through and resolve some conflicts. Can discard repository.py

### CODE REVIEW

**Comment by bahag-chaudharyl** [comment]
should be fine now!
do we need to check if location is not in data in add_event methods?

**Comment by donadivarun** [comment]
> should be fine now! do we need to check if location is not in data in add_event methods?

Maybe, since we want to pass all data to sql and location is optional, if its not there we just pass an empty string. Idk how to modify sql query based on inputs.

**Comment by bahag-chaudharyl** [comment]
> > should be fine now! do we need to check if location is not in data in add_event methods?
> 
> Maybe, since we want to pass all data to sql and location is optional, if its not there we just pass an empty string. Idk how to modify sql query based on inputs.

all the add events will come from the frontend form, which already has a location field, even if we leave it blank, it will treat it as an empty string

**Comment by donadivarun** [comment]
> > > should be fine now! do we need to check if location is not in data in add_event methods?
> > 
> > 
> > Maybe, since we want to pass all data to sql and location is optional, if its not there we just pass an empty string. Idk how to modify sql query based on inputs.
> 
> all the add events will come from the frontend form, which already has a location field, even if we leave it blank, it will treat it as an empty string

Then its okay I guess. I didnt know how or what we would get from front end. then you can merge it :)

**Comment by bahag-chaudharyl** [comment]
Done! :)

**Pull request merged**
